#!/usr/bin/env python3
N = int(input())
S = list(input())
dp = [[0] * N for i in range(3)] 
W = {"P":2, "R":0, "S":1}
L = {"P":1, "R":2, "S":0}
dp[W[S[0]]][0] = 1
dp[L[S[0]]][0] = -1
for n in range(1, N):
    dp[0][n] = max(dp[1][n - 1], dp[2][n - 1])
    dp[1][n] = max(dp[2][n - 1], dp[0][n - 1])
    dp[2][n] = max(dp[0][n - 1], dp[1][n - 1])
    dp[W[S[n]]][n] += 1
    dp[L[S[n]]][n] = -1
print(max(dp[-1]))