#!/usr/bin/env python3
def aa(m):
  ans=0
  for i in range(n):
    c=1<<60
    q,w,e,r=v[i]
    for j in range(v[i][0]):
      s=m-j
      c=min(c,r*j+dp[i][q*e]*(s//(q*e))+dp[i][s%(q*e)])
    for j in range(e):
      s=m-j
      c=min(c,w*j+dp[i][q*e]*(s//(q*e))+dp[i][s%(q*e)])
    ans+=c
  return ans

n,x=map(int,input().split())
v=[list(map(int,input().split())) for i in range(n)]
dp=[[1<<60]*(10001) for i in range(n)]
for i in range(n):
  dp[i][0]=0
  for j in range(10001):
    if j+v[i][0]<=10000:
      dp[i][j+v[i][0]]=min(dp[i][j+v[i][0]],v[i][1]+dp[i][j])
    if j+v[i][2]<=10000:
      dp[i][j+v[i][2]]=min(dp[i][j+v[i][2]],v[i][3]+dp[i][j])
  for j in range(10000,0,-1):
    dp[i][j-1]=min(dp[i][j-1],dp[i][j])
q,w=0,1<<30
while w-q>1:
  m=(q+w)//2
  if aa(m)<=x:
    q=m
  else:
    w=m
print(q)